### ISSUE TITLE
Player redesign

### ISSUE THREAD

**Issue by z-huang** [z-huang/music#253]
- [ ] [Length of long music is shortened in player, though full song plays #49](https://github.com/z-huang/music/issues/49)
- [ ] [Double tap to seek songs #96](https://github.com/z-huang/music/issues/96)
- [ ] [Sleep timer #97](https://github.com/z-huang/music/issues/97)
- [ ] [Player seek bar inaccurate (at last position) #103](https://github.com/z-huang/music/issues/103)
- [ ] [Download button in player #105](https://github.com/z-huang/music/issues/105)
- [ ] ["Song info" button in now playing screen #122](https://github.com/z-huang/music/issues/122)
- [ ] [Slideup window in player bottom sheet #128](https://github.com/z-huang/music/issues/128)
- [ ] [Improve landscape mode #227](https://github.com/z-huang/music/issues/227)
- [ ] [Queue improvement #252](https://github.com/z-huang/music/issues/252)
